import { useState } from "react";
import styles from "./ActiveAlerts.module.css";
import { useSurveillance } from "../context/SurveillanceContext";

function ActiveAlerts() {

    const {
        threats: alerts,
        acknowledgeThreat,
        activeThreats: activeAlerts,
        criticalThreats: criticalAlerts,
        highThreats: highAlerts,
        mediumThreats: mediumAlerts,
        viewCameraLive
    } = useSurveillance();

    const [selectedAlert, setSelectedAlert] = useState(null);


    const acknowledgeAlert = (id) => {

        acknowledgeThreat(id);

        setSelectedAlert(null);

    };


    const handleViewCamera = () => {

        if (!selectedAlert) return;


        viewCameraLive(selectedAlert.cameraId);

        setSelectedAlert(null);

    };


    return (

        <div className={styles.alertsPage}>

            {/* ================= TOP ================= */}

            <div className={styles.top}>

                <div>

                    <h2>ACTIVE ALERTS</h2>

                    <p>
                        Real-time security alerts requiring attention
                    </p>

                </div>


                <div className={styles.liveStatus}>
                    ● ALERT MONITORING ACTIVE
                </div>

            </div>


            {/* ================= STATISTICS ================= */}

            <div className={styles.stats}>

                <div className={styles.statCard}>

                    <span>ACTIVE ALERTS</span>

                    <h3>
                        {activeAlerts.length}
                    </h3>

                    <p>
                        Currently requiring attention
                    </p>

                </div>


                <div className={styles.statCard}>

                    <span>CRITICAL</span>

                    <h3 className={styles.critical}>
                        {criticalAlerts.length}
                    </h3>

                    <p>
                        Immediate response required
                    </p>

                </div>


                <div className={styles.statCard}>

                    <span>HIGH PRIORITY</span>

                    <h3 className={styles.high}>
                        {highAlerts.length}
                    </h3>

                    <p>
                        Requires investigation
                    </p>

                </div>


                <div className={styles.statCard}>

                    <span>MEDIUM</span>

                    <h3 className={styles.medium}>
                        {mediumAlerts.length}
                    </h3>

                    <p>
                        Under monitoring
                    </p>

                </div>

            </div>


            {/* ================= ALERT PANEL ================= */}

            <div className={styles.alertPanel}>

                <div className={styles.panelHeader}>

                    <div>

                        <h3>
                            🚨 SECURITY ALERTS
                        </h3>

                        <p>
                            Latest alerts generated by the AI detection system
                        </p>

                    </div>


                    <span>
                        {activeAlerts.length} ACTIVE
                    </span>

                </div>


                <div className={styles.alertList}>

                    {alerts.map((alert) => (

                        <div
                            key={alert.id}
                            className={`${styles.alertItem} ${
                                alert.status === "ACKNOWLEDGED"
                                    ? styles.acknowledged
                                    : ""
                            }`}
                        >

                            <div className={styles.alertIcon}>
                                {alert.icon}
                            </div>


                            <div className={styles.alertInfo}>

                                <div className={styles.alertTitleRow}>

                                    <h4>
                                        {alert.title}
                                    </h4>


                                    <span
                                        className={
                                            alert.severity === "CRITICAL"
                                                ? styles.criticalBadge
                                                : alert.severity === "HIGH"
                                                    ? styles.highBadge
                                                    : styles.mediumBadge
                                        }
                                    >

                                        {alert.severity}

                                    </span>

                                </div>


                                <p>

                                    📹 {alert.camera}

                                    <span>
                                        {" • "}
                                    </span>

                                    📍 {alert.location}

                                </p>


                                <div className={styles.alertMeta}>

                                    <span>
                                        AI Confidence: {alert.confidence}
                                    </span>

                                    <span>
                                        Detected: {alert.time}
                                    </span>

                                </div>

                            </div>


                            <div className={styles.alertStatus}>

                                <span
                                    className={
                                        alert.status === "ACTIVE"
                                            ? styles.activeStatus
                                            : styles.acknowledgedStatus
                                    }
                                >

                                    ● {alert.status}

                                </span>

                            </div>


                            <div className={styles.alertAction}>

                                {alert.status === "ACTIVE" && (

                                    <button
                                        onClick={() =>
                                            setSelectedAlert(alert)
                                        }
                                    >

                                        VIEW

                                    </button>

                                )}

                            </div>

                        </div>

                    ))}

                </div>

            </div>


            {/* ================= DETAILS MODAL ================= */}

            {selectedAlert && (

                <div
                    className={styles.modalOverlay}
                    onClick={() =>
                        setSelectedAlert(null)
                    }
                >

                    <div
                        className={styles.modal}
                        onClick={(event) =>
                            event.stopPropagation()
                        }
                    >

                        <div className={styles.modalHeader}>

                            <div>

                                <h3>
                                    ALERT DETAILS
                                </h3>

                                <p>
                                    Security event information
                                </p>

                            </div>


                            <button
                                className={styles.closeButton}
                                onClick={() =>
                                    setSelectedAlert(null)
                                }
                            >

                                ✕

                            </button>

                        </div>


                        <div className={styles.modalTitle}>

                            <div className={styles.modalIcon}>

                                {selectedAlert.icon}

                            </div>


                            <div>

                                <h2>
                                    {selectedAlert.title}
                                </h2>


                                <span
                                    className={
                                        selectedAlert.severity === "CRITICAL"
                                            ? styles.criticalText
                                            : selectedAlert.severity === "HIGH"
                                                ? styles.highText
                                                : styles.mediumText
                                    }
                                >

                                    ● {selectedAlert.severity}

                                </span>

                            </div>

                        </div>


                        <div className={styles.description}>

                            <span>
                                AI ANALYSIS
                            </span>

                            <p>
                                {selectedAlert.description}
                            </p>

                        </div>


                        <div className={styles.detailsGrid}>

                            <div>

                                <span>
                                    CAMERA
                                </span>

                                <strong>
                                    {selectedAlert.camera}
                                </strong>

                            </div>


                            <div>

                                <span>
                                    LOCATION
                                </span>

                                <strong>
                                    {selectedAlert.location}
                                </strong>

                            </div>


                            <div>

                                <span>
                                    CONFIDENCE
                                </span>

                                <strong>
                                    {selectedAlert.confidence}
                                </strong>

                            </div>


                            <div>

                                <span>
                                    DETECTED AT
                                </span>

                                <strong>
                                    {selectedAlert.time}
                                </strong>

                            </div>

                        </div>


                        <div className={styles.modalActions}>

                            <button
                                className={styles.cameraButton}
                                onClick={handleViewCamera}
                            >

                                📹 VIEW CAMERA

                            </button>


                            <button
                                className={styles.acknowledgeButton}
                                onClick={() =>
                                    acknowledgeAlert(
                                        selectedAlert.id
                                    )
                                }
                            >

                                ✓ ACKNOWLEDGE

                            </button>

                        </div>

                    </div>

                </div>

            )}

        </div>

    );

}

export default ActiveAlerts;